public class TestPageController 
{  
    /*--- @TODO For Future Use... (Als backend VF page admin stuff)
    public String getObjType() 
    {
        return String.valueOf(Account.sObjectType);
    }
    
    public RoleUtil.RoleNodeWrapper getRootNodeOfTree(Id roleOrUserId) 
    {
        return RoleUtil.getRootNodeOfUserTree(roleOrUserId);
    }

    public String getJsonString() 
    {
        String str = null;
        str = RoleUtil.getTreeJSON('00E90000000pMaP');
        return str; 
    }
    
    public String selectedValues {get; set;}
    */

}